//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 

namespace TCG.PaymentGatewayLibrary.MyGateBankAccountVerification
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "MyGate_AccVerification_WebServices.cfcSoapBinding", Namespace = "http://includes.debitorders")]
    public partial class Mygate_accverification_webservicesService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ImportAccountsToValidateOperationCompleted;

        private System.Threading.SendOrPostCallback downloadResponseFilesOperationCompleted;

        /// <remarks/>
        public Mygate_accverification_webservicesService()
        {
            this.Url = "http://www.mygate.co.za/debitorders/includes/MyGate_AccVerification_WebServices.c" +
                "fc";
        }

        /// <remarks/>
        public event ImportAccountsToValidateCompletedEventHandler ImportAccountsToValidateCompleted;

        /// <remarks/>
        public event downloadResponseFilesCompletedEventHandler downloadResponseFilesCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://includes.debitorders", ResponseNamespace = "http://includes.debitorders")]
        [return: System.Xml.Serialization.SoapElementAttribute("ImportAccountsToValidateReturn")]
        public string ImportAccountsToValidate(string accValidationXML)
        {
            object[] results = this.Invoke("ImportAccountsToValidate", new object[] {
                    accValidationXML});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginImportAccountsToValidate(string accValidationXML, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ImportAccountsToValidate", new object[] {
                    accValidationXML}, callback, asyncState);
        }

        /// <remarks/>
        public string EndImportAccountsToValidate(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ImportAccountsToValidateAsync(string accValidationXML)
        {
            this.ImportAccountsToValidateAsync(accValidationXML, null);
        }

        /// <remarks/>
        public void ImportAccountsToValidateAsync(string accValidationXML, object userState)
        {
            if ((this.ImportAccountsToValidateOperationCompleted == null))
            {
                this.ImportAccountsToValidateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportAccountsToValidateOperationCompleted);
            }
            this.InvokeAsync("ImportAccountsToValidate", new object[] {
                    accValidationXML}, this.ImportAccountsToValidateOperationCompleted, userState);
        }

        private void OnImportAccountsToValidateOperationCompleted(object arg)
        {
            if ((this.ImportAccountsToValidateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportAccountsToValidateCompleted(this, new ImportAccountsToValidateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://includes.debitorders", ResponseNamespace = "http://includes.debitorders")]
        [return: System.Xml.Serialization.SoapElementAttribute("downloadResponseFilesReturn")]
        public string downloadResponseFiles(string inputXML)
        {
            object[] results = this.Invoke("downloadResponseFiles", new object[] {
                    inputXML});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegindownloadResponseFiles(string inputXML, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("downloadResponseFiles", new object[] {
                    inputXML}, callback, asyncState);
        }

        /// <remarks/>
        public string EnddownloadResponseFiles(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void downloadResponseFilesAsync(string inputXML)
        {
            this.downloadResponseFilesAsync(inputXML, null);
        }

        /// <remarks/>
        public void downloadResponseFilesAsync(string inputXML, object userState)
        {
            if ((this.downloadResponseFilesOperationCompleted == null))
            {
                this.downloadResponseFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadResponseFilesOperationCompleted);
            }
            this.InvokeAsync("downloadResponseFiles", new object[] {
                    inputXML}, this.downloadResponseFilesOperationCompleted, userState);
        }

        private void OndownloadResponseFilesOperationCompleted(object arg)
        {
            if ((this.downloadResponseFilesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadResponseFilesCompleted(this, new downloadResponseFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void ImportAccountsToValidateCompletedEventHandler(object sender, ImportAccountsToValidateCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportAccountsToValidateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ImportAccountsToValidateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void downloadResponseFilesCompletedEventHandler(object sender, downloadResponseFilesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadResponseFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal downloadResponseFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

}

