//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace TCG.PaymentGatewayLibrary.SagePayNetCashPartner
{
    // 
    // This source code was auto-generated by wsdl, Version=4.6.81.0.
    // 


    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'EndpointReference' from namespace 'http://www.w3.org/2005/08/addressing' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WSHttpBinding_INIWS_Partner", Namespace = "http://tempuri.org/")]
    public partial class NIWS_Partner : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback BatchFileUploadOperationCompleted;

        private System.Threading.SendOrPostCallback RequestFileUploadReportOperationCompleted;

        private System.Threading.SendOrPostCallback ValidateServiceKeyOperationCompleted;

        private System.Threading.SendOrPostCallback AccountSupportMessageOperationCompleted;

        private System.Threading.SendOrPostCallback RequestAccountStatusOperationCompleted;

        private System.Threading.SendOrPostCallback RetrieveAccountStatusOperationCompleted;

        /// <remarks/>
        public NIWS_Partner()
        {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "https://ws.sagepay.co.za/NIWS/NIWS_Partner.svc";
        }

        /// <remarks/>
        public event BatchFileUploadCompletedEventHandler BatchFileUploadCompleted;

        /// <remarks/>
        public event RequestFileUploadReportCompletedEventHandler RequestFileUploadReportCompleted;

        /// <remarks/>
        public event ValidateServiceKeyCompletedEventHandler ValidateServiceKeyCompleted;

        /// <remarks/>
        public event AccountSupportMessageCompletedEventHandler AccountSupportMessageCompleted;

        /// <remarks/>
        public event RequestAccountStatusCompletedEventHandler RequestAccountStatusCompleted;

        /// <remarks/>
        public event RetrieveAccountStatusCompletedEventHandler RetrieveAccountStatusCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INIWS_Partner/BatchFileUpload", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BatchFileUpload([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string serviceKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string file)
        {
            object[] results = this.Invoke("BatchFileUpload", new object[] {
                    serviceKey,
                    file});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginBatchFileUpload(string serviceKey, string file, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("BatchFileUpload", new object[] {
                    serviceKey,
                    file}, callback, asyncState);
        }

        /// <remarks/>
        public string EndBatchFileUpload(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void BatchFileUploadAsync(string serviceKey, string file)
        {
            this.BatchFileUploadAsync(serviceKey, file, null);
        }

        /// <remarks/>
        public void BatchFileUploadAsync(string serviceKey, string file, object userState)
        {
            if ((this.BatchFileUploadOperationCompleted == null))
            {
                this.BatchFileUploadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBatchFileUploadOperationCompleted);
            }
            this.InvokeAsync("BatchFileUpload", new object[] {
                    serviceKey,
                    file}, this.BatchFileUploadOperationCompleted, userState);
        }

        private void OnBatchFileUploadOperationCompleted(object arg)
        {
            if ((this.BatchFileUploadCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BatchFileUploadCompleted(this, new BatchFileUploadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INIWS_Partner/RequestFileUploadReport", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RequestFileUploadReport([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string serviceKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string fileToken)
        {
            object[] results = this.Invoke("RequestFileUploadReport", new object[] {
                    serviceKey,
                    fileToken});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRequestFileUploadReport(string serviceKey, string fileToken, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RequestFileUploadReport", new object[] {
                    serviceKey,
                    fileToken}, callback, asyncState);
        }

        /// <remarks/>
        public string EndRequestFileUploadReport(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void RequestFileUploadReportAsync(string serviceKey, string fileToken)
        {
            this.RequestFileUploadReportAsync(serviceKey, fileToken, null);
        }

        /// <remarks/>
        public void RequestFileUploadReportAsync(string serviceKey, string fileToken, object userState)
        {
            if ((this.RequestFileUploadReportOperationCompleted == null))
            {
                this.RequestFileUploadReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestFileUploadReportOperationCompleted);
            }
            this.InvokeAsync("RequestFileUploadReport", new object[] {
                    serviceKey,
                    fileToken}, this.RequestFileUploadReportOperationCompleted, userState);
        }

        private void OnRequestFileUploadReportOperationCompleted(object arg)
        {
            if ((this.RequestFileUploadReportCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestFileUploadReportCompleted(this, new RequestFileUploadReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INIWS_Partner/ValidateServiceKey", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ValidateServiceKeyResponse ValidateServiceKey([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] ValidateServiceKeyRequest request)
        {
            object[] results = this.Invoke("ValidateServiceKey", new object[] {
                    request});
            return ((ValidateServiceKeyResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginValidateServiceKey(ValidateServiceKeyRequest request, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ValidateServiceKey", new object[] {
                    request}, callback, asyncState);
        }

        /// <remarks/>
        public ValidateServiceKeyResponse EndValidateServiceKey(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ValidateServiceKeyResponse)(results[0]));
        }

        /// <remarks/>
        public void ValidateServiceKeyAsync(ValidateServiceKeyRequest request)
        {
            this.ValidateServiceKeyAsync(request, null);
        }

        /// <remarks/>
        public void ValidateServiceKeyAsync(ValidateServiceKeyRequest request, object userState)
        {
            if ((this.ValidateServiceKeyOperationCompleted == null))
            {
                this.ValidateServiceKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateServiceKeyOperationCompleted);
            }
            this.InvokeAsync("ValidateServiceKey", new object[] {
                    request}, this.ValidateServiceKeyOperationCompleted, userState);
        }

        private void OnValidateServiceKeyOperationCompleted(object arg)
        {
            if ((this.ValidateServiceKeyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateServiceKeyCompleted(this, new ValidateServiceKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INIWS_Partner/AccountSupportMessage", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AccountSupportMessage([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string partnerServiceKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string serviceKey)
        {
            object[] results = this.Invoke("AccountSupportMessage", new object[] {
                    partnerServiceKey,
                    serviceKey});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginAccountSupportMessage(string partnerServiceKey, string serviceKey, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("AccountSupportMessage", new object[] {
                    partnerServiceKey,
                    serviceKey}, callback, asyncState);
        }

        /// <remarks/>
        public string EndAccountSupportMessage(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void AccountSupportMessageAsync(string partnerServiceKey, string serviceKey)
        {
            this.AccountSupportMessageAsync(partnerServiceKey, serviceKey, null);
        }

        /// <remarks/>
        public void AccountSupportMessageAsync(string partnerServiceKey, string serviceKey, object userState)
        {
            if ((this.AccountSupportMessageOperationCompleted == null))
            {
                this.AccountSupportMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountSupportMessageOperationCompleted);
            }
            this.InvokeAsync("AccountSupportMessage", new object[] {
                    partnerServiceKey,
                    serviceKey}, this.AccountSupportMessageOperationCompleted, userState);
        }

        private void OnAccountSupportMessageOperationCompleted(object arg)
        {
            if ((this.AccountSupportMessageCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountSupportMessageCompleted(this, new AccountSupportMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INIWS_Partner/RequestAccountStatus", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RequestAccountStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string partnerServiceKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string pastelAccountNo)
        {
            object[] results = this.Invoke("RequestAccountStatus", new object[] {
                    partnerServiceKey,
                    pastelAccountNo});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRequestAccountStatus(string partnerServiceKey, string pastelAccountNo, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RequestAccountStatus", new object[] {
                    partnerServiceKey,
                    pastelAccountNo}, callback, asyncState);
        }

        /// <remarks/>
        public string EndRequestAccountStatus(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void RequestAccountStatusAsync(string partnerServiceKey, string pastelAccountNo)
        {
            this.RequestAccountStatusAsync(partnerServiceKey, pastelAccountNo, null);
        }

        /// <remarks/>
        public void RequestAccountStatusAsync(string partnerServiceKey, string pastelAccountNo, object userState)
        {
            if ((this.RequestAccountStatusOperationCompleted == null))
            {
                this.RequestAccountStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestAccountStatusOperationCompleted);
            }
            this.InvokeAsync("RequestAccountStatus", new object[] {
                    partnerServiceKey,
                    pastelAccountNo}, this.RequestAccountStatusOperationCompleted, userState);
        }

        private void OnRequestAccountStatusOperationCompleted(object arg)
        {
            if ((this.RequestAccountStatusCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestAccountStatusCompleted(this, new RequestAccountStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INIWS_Partner/RetrieveAccountStatus", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RetrieveAccountStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string ServiceKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string FileToken)
        {
            object[] results = this.Invoke("RetrieveAccountStatus", new object[] {
                    ServiceKey,
                    FileToken});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRetrieveAccountStatus(string ServiceKey, string FileToken, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RetrieveAccountStatus", new object[] {
                    ServiceKey,
                    FileToken}, callback, asyncState);
        }

        /// <remarks/>
        public string EndRetrieveAccountStatus(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void RetrieveAccountStatusAsync(string ServiceKey, string FileToken)
        {
            this.RetrieveAccountStatusAsync(ServiceKey, FileToken, null);
        }

        /// <remarks/>
        public void RetrieveAccountStatusAsync(string ServiceKey, string FileToken, object userState)
        {
            if ((this.RetrieveAccountStatusOperationCompleted == null))
            {
                this.RetrieveAccountStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveAccountStatusOperationCompleted);
            }
            this.InvokeAsync("RetrieveAccountStatus", new object[] {
                    ServiceKey,
                    FileToken}, this.RetrieveAccountStatusOperationCompleted, userState);
        }

        private void OnRetrieveAccountStatusOperationCompleted(object arg)
        {
            if ((this.RetrieveAccountStatusCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveAccountStatusCompleted(this, new RetrieveAccountStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class ValidateServiceKeyRequest
    {

        private string merchantAccountField;

        private ServiceInfo[] serviceInfoListField;

        private string softwareVendorKeyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MerchantAccount
        {
            get
            {
                return this.merchantAccountField;
            }
            set
            {
                this.merchantAccountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public ServiceInfo[] ServiceInfoList
        {
            get
            {
                return this.serviceInfoListField;
            }
            set
            {
                this.serviceInfoListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SoftwareVendorKey
        {
            get
            {
                return this.softwareVendorKeyField;
            }
            set
            {
                this.softwareVendorKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class ServiceInfo
    {

        private string serviceIdField;

        private string serviceKeyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ServiceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ServiceKey
        {
            get
            {
                return this.serviceKeyField;
            }
            set
            {
                this.serviceKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class ServiceInfoResponse
    {

        private string serviceIdField;

        private string serviceKeyField;

        private string serviceStatusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ServiceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ServiceKey
        {
            get
            {
                return this.serviceKeyField;
            }
            set
            {
                this.serviceKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ServiceStatus
        {
            get
            {
                return this.serviceStatusField;
            }
            set
            {
                this.serviceStatusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class ValidateServiceKeyResponse
    {

        private string accountStatusField;

        private string merchantAccountField;

        private ServiceInfoResponse[] serviceInfoField;

        private string softwareVendorKeyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AccountStatus
        {
            get
            {
                return this.accountStatusField;
            }
            set
            {
                this.accountStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MerchantAccount
        {
            get
            {
                return this.merchantAccountField;
            }
            set
            {
                this.merchantAccountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public ServiceInfoResponse[] ServiceInfo
        {
            get
            {
                return this.serviceInfoField;
            }
            set
            {
                this.serviceInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SoftwareVendorKey
        {
            get
            {
                return this.softwareVendorKeyField;
            }
            set
            {
                this.softwareVendorKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void BatchFileUploadCompletedEventHandler(object sender, BatchFileUploadCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BatchFileUploadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal BatchFileUploadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void RequestFileUploadReportCompletedEventHandler(object sender, RequestFileUploadReportCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestFileUploadReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RequestFileUploadReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void ValidateServiceKeyCompletedEventHandler(object sender, ValidateServiceKeyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateServiceKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ValidateServiceKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ValidateServiceKeyResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ValidateServiceKeyResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void AccountSupportMessageCompletedEventHandler(object sender, AccountSupportMessageCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountSupportMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal AccountSupportMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void RequestAccountStatusCompletedEventHandler(object sender, RequestAccountStatusCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestAccountStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RequestAccountStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void RetrieveAccountStatusCompletedEventHandler(object sender, RetrieveAccountStatusCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveAccountStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RetrieveAccountStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }


}

