//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.81.0.
// 

namespace TCG.PaymentGatewayLibrary.VCSTokenisation
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "Svc_VirtualRecurSoap", Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class Svc_VirtualRecur : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback AddCCTransactionOperationCompleted;

        private System.Threading.SendOrPostCallback UpdateCCTransactionOperationCompleted;

        private System.Threading.SendOrPostCallback UpdateCCNumberOperationCompleted;

        private System.Threading.SendOrPostCallback UnSuspendCCTransactionOperationCompleted;

        private System.Threading.SendOrPostCallback SuspendCCTransactionOperationCompleted;

        private System.Threading.SendOrPostCallback ActivateCCTransactionOperationCompleted;

        private System.Threading.SendOrPostCallback DeleteCCTransactionOperationCompleted;

        private System.Threading.SendOrPostCallback GetCCTransactionListOperationCompleted;

        private System.Threading.SendOrPostCallback GetCCTransactionDetailOperationCompleted;

        /// <remarks/>
        public Svc_VirtualRecur()
        {
            this.Url = "https://www.vcs.co.za/wscs/svc_VirtualRecur.asmx";
        }

        /// <remarks/>
        public event AddCCTransactionCompletedEventHandler AddCCTransactionCompleted;

        /// <remarks/>
        public event UpdateCCTransactionCompletedEventHandler UpdateCCTransactionCompleted;

        /// <remarks/>
        public event UpdateCCNumberCompletedEventHandler UpdateCCNumberCompleted;

        /// <remarks/>
        public event UnSuspendCCTransactionCompletedEventHandler UnSuspendCCTransactionCompleted;

        /// <remarks/>
        public event SuspendCCTransactionCompletedEventHandler SuspendCCTransactionCompleted;

        /// <remarks/>
        public event ActivateCCTransactionCompletedEventHandler ActivateCCTransactionCompleted;

        /// <remarks/>
        public event DeleteCCTransactionCompletedEventHandler DeleteCCTransactionCompleted;

        /// <remarks/>
        public event GetCCTransactionListCompletedEventHandler GetCCTransactionListCompleted;

        /// <remarks/>
        public event GetCCTransactionDetailCompletedEventHandler GetCCTransactionDetailCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vcs.co.za/wscs/svc_virtualrecur.asmx/AddCCTransaction", RequestNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", ResponseNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddCCResponse AddCCTransaction(AddCCRequest AddCCRequest)
        {
            object[] results = this.Invoke("AddCCTransaction", new object[] {
                    AddCCRequest});
            return ((AddCCResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginAddCCTransaction(AddCCRequest AddCCRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("AddCCTransaction", new object[] {
                    AddCCRequest}, callback, asyncState);
        }

        /// <remarks/>
        public AddCCResponse EndAddCCTransaction(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((AddCCResponse)(results[0]));
        }

        /// <remarks/>
        public void AddCCTransactionAsync(AddCCRequest AddCCRequest)
        {
            this.AddCCTransactionAsync(AddCCRequest, null);
        }

        /// <remarks/>
        public void AddCCTransactionAsync(AddCCRequest AddCCRequest, object userState)
        {
            if ((this.AddCCTransactionOperationCompleted == null))
            {
                this.AddCCTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCCTransactionOperationCompleted);
            }
            this.InvokeAsync("AddCCTransaction", new object[] {
                    AddCCRequest}, this.AddCCTransactionOperationCompleted, userState);
        }

        private void OnAddCCTransactionOperationCompleted(object arg)
        {
            if ((this.AddCCTransactionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCCTransactionCompleted(this, new AddCCTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vcs.co.za/wscs/svc_virtualrecur.asmx/UpdateCCTransaction", RequestNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", ResponseNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UpdateCCResponse UpdateCCTransaction(UpdateCCRequest UpdateCCRequest)
        {
            object[] results = this.Invoke("UpdateCCTransaction", new object[] {
                    UpdateCCRequest});
            return ((UpdateCCResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUpdateCCTransaction(UpdateCCRequest UpdateCCRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateCCTransaction", new object[] {
                    UpdateCCRequest}, callback, asyncState);
        }

        /// <remarks/>
        public UpdateCCResponse EndUpdateCCTransaction(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((UpdateCCResponse)(results[0]));
        }

        /// <remarks/>
        public void UpdateCCTransactionAsync(UpdateCCRequest UpdateCCRequest)
        {
            this.UpdateCCTransactionAsync(UpdateCCRequest, null);
        }

        /// <remarks/>
        public void UpdateCCTransactionAsync(UpdateCCRequest UpdateCCRequest, object userState)
        {
            if ((this.UpdateCCTransactionOperationCompleted == null))
            {
                this.UpdateCCTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCCTransactionOperationCompleted);
            }
            this.InvokeAsync("UpdateCCTransaction", new object[] {
                    UpdateCCRequest}, this.UpdateCCTransactionOperationCompleted, userState);
        }

        private void OnUpdateCCTransactionOperationCompleted(object arg)
        {
            if ((this.UpdateCCTransactionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCCTransactionCompleted(this, new UpdateCCTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vcs.co.za/wscs/svc_virtualrecur.asmx/UpdateCCNumber", RequestNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", ResponseNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UpdateCCNumberResponse UpdateCCNumber(UpdateCCNumberRequest UpdateCCNumberRequest)
        {
            object[] results = this.Invoke("UpdateCCNumber", new object[] {
                    UpdateCCNumberRequest});
            return ((UpdateCCNumberResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUpdateCCNumber(UpdateCCNumberRequest UpdateCCNumberRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateCCNumber", new object[] {
                    UpdateCCNumberRequest}, callback, asyncState);
        }

        /// <remarks/>
        public UpdateCCNumberResponse EndUpdateCCNumber(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((UpdateCCNumberResponse)(results[0]));
        }

        /// <remarks/>
        public void UpdateCCNumberAsync(UpdateCCNumberRequest UpdateCCNumberRequest)
        {
            this.UpdateCCNumberAsync(UpdateCCNumberRequest, null);
        }

        /// <remarks/>
        public void UpdateCCNumberAsync(UpdateCCNumberRequest UpdateCCNumberRequest, object userState)
        {
            if ((this.UpdateCCNumberOperationCompleted == null))
            {
                this.UpdateCCNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCCNumberOperationCompleted);
            }
            this.InvokeAsync("UpdateCCNumber", new object[] {
                    UpdateCCNumberRequest}, this.UpdateCCNumberOperationCompleted, userState);
        }

        private void OnUpdateCCNumberOperationCompleted(object arg)
        {
            if ((this.UpdateCCNumberCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCCNumberCompleted(this, new UpdateCCNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vcs.co.za/wscs/svc_virtualrecur.asmx/UnSuspendCCTransaction", RequestNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", ResponseNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UnSuspendCCResponse UnSuspendCCTransaction(UnSuspendCCRequest UnSuspendCCRequest)
        {
            object[] results = this.Invoke("UnSuspendCCTransaction", new object[] {
                    UnSuspendCCRequest});
            return ((UnSuspendCCResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUnSuspendCCTransaction(UnSuspendCCRequest UnSuspendCCRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UnSuspendCCTransaction", new object[] {
                    UnSuspendCCRequest}, callback, asyncState);
        }

        /// <remarks/>
        public UnSuspendCCResponse EndUnSuspendCCTransaction(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((UnSuspendCCResponse)(results[0]));
        }

        /// <remarks/>
        public void UnSuspendCCTransactionAsync(UnSuspendCCRequest UnSuspendCCRequest)
        {
            this.UnSuspendCCTransactionAsync(UnSuspendCCRequest, null);
        }

        /// <remarks/>
        public void UnSuspendCCTransactionAsync(UnSuspendCCRequest UnSuspendCCRequest, object userState)
        {
            if ((this.UnSuspendCCTransactionOperationCompleted == null))
            {
                this.UnSuspendCCTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnSuspendCCTransactionOperationCompleted);
            }
            this.InvokeAsync("UnSuspendCCTransaction", new object[] {
                    UnSuspendCCRequest}, this.UnSuspendCCTransactionOperationCompleted, userState);
        }

        private void OnUnSuspendCCTransactionOperationCompleted(object arg)
        {
            if ((this.UnSuspendCCTransactionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnSuspendCCTransactionCompleted(this, new UnSuspendCCTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vcs.co.za/wscs/svc_virtualrecur.asmx/SuspendCCTransaction", RequestNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", ResponseNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SuspendCCResponse SuspendCCTransaction(SuspendCCRequest SuspendCCRequest)
        {
            object[] results = this.Invoke("SuspendCCTransaction", new object[] {
                    SuspendCCRequest});
            return ((SuspendCCResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSuspendCCTransaction(SuspendCCRequest SuspendCCRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SuspendCCTransaction", new object[] {
                    SuspendCCRequest}, callback, asyncState);
        }

        /// <remarks/>
        public SuspendCCResponse EndSuspendCCTransaction(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((SuspendCCResponse)(results[0]));
        }

        /// <remarks/>
        public void SuspendCCTransactionAsync(SuspendCCRequest SuspendCCRequest)
        {
            this.SuspendCCTransactionAsync(SuspendCCRequest, null);
        }

        /// <remarks/>
        public void SuspendCCTransactionAsync(SuspendCCRequest SuspendCCRequest, object userState)
        {
            if ((this.SuspendCCTransactionOperationCompleted == null))
            {
                this.SuspendCCTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuspendCCTransactionOperationCompleted);
            }
            this.InvokeAsync("SuspendCCTransaction", new object[] {
                    SuspendCCRequest}, this.SuspendCCTransactionOperationCompleted, userState);
        }

        private void OnSuspendCCTransactionOperationCompleted(object arg)
        {
            if ((this.SuspendCCTransactionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuspendCCTransactionCompleted(this, new SuspendCCTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vcs.co.za/wscs/svc_virtualrecur.asmx/ActivateCCTransaction", RequestNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", ResponseNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActivateCCResponse ActivateCCTransaction(ActivateCCRequest ActivateCCRequest)
        {
            object[] results = this.Invoke("ActivateCCTransaction", new object[] {
                    ActivateCCRequest});
            return ((ActivateCCResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginActivateCCTransaction(ActivateCCRequest ActivateCCRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ActivateCCTransaction", new object[] {
                    ActivateCCRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ActivateCCResponse EndActivateCCTransaction(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ActivateCCResponse)(results[0]));
        }

        /// <remarks/>
        public void ActivateCCTransactionAsync(ActivateCCRequest ActivateCCRequest)
        {
            this.ActivateCCTransactionAsync(ActivateCCRequest, null);
        }

        /// <remarks/>
        public void ActivateCCTransactionAsync(ActivateCCRequest ActivateCCRequest, object userState)
        {
            if ((this.ActivateCCTransactionOperationCompleted == null))
            {
                this.ActivateCCTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateCCTransactionOperationCompleted);
            }
            this.InvokeAsync("ActivateCCTransaction", new object[] {
                    ActivateCCRequest}, this.ActivateCCTransactionOperationCompleted, userState);
        }

        private void OnActivateCCTransactionOperationCompleted(object arg)
        {
            if ((this.ActivateCCTransactionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateCCTransactionCompleted(this, new ActivateCCTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vcs.co.za/wscs/svc_virtualrecur.asmx/DeleteCCTransaction", RequestNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", ResponseNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeleteCCResponse DeleteCCTransaction(DeleteCCRequest DeleteCCRequest)
        {
            object[] results = this.Invoke("DeleteCCTransaction", new object[] {
                    DeleteCCRequest});
            return ((DeleteCCResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDeleteCCTransaction(DeleteCCRequest DeleteCCRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DeleteCCTransaction", new object[] {
                    DeleteCCRequest}, callback, asyncState);
        }

        /// <remarks/>
        public DeleteCCResponse EndDeleteCCTransaction(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((DeleteCCResponse)(results[0]));
        }

        /// <remarks/>
        public void DeleteCCTransactionAsync(DeleteCCRequest DeleteCCRequest)
        {
            this.DeleteCCTransactionAsync(DeleteCCRequest, null);
        }

        /// <remarks/>
        public void DeleteCCTransactionAsync(DeleteCCRequest DeleteCCRequest, object userState)
        {
            if ((this.DeleteCCTransactionOperationCompleted == null))
            {
                this.DeleteCCTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCCTransactionOperationCompleted);
            }
            this.InvokeAsync("DeleteCCTransaction", new object[] {
                    DeleteCCRequest}, this.DeleteCCTransactionOperationCompleted, userState);
        }

        private void OnDeleteCCTransactionOperationCompleted(object arg)
        {
            if ((this.DeleteCCTransactionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCCTransactionCompleted(this, new DeleteCCTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vcs.co.za/wscs/svc_virtualrecur.asmx/GetCCTransactionList", RequestNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", ResponseNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetCCListResponse GetCCTransactionList(GetCCListRequest GetCCListRequest)
        {
            object[] results = this.Invoke("GetCCTransactionList", new object[] {
                    GetCCListRequest});
            return ((GetCCListResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetCCTransactionList(GetCCListRequest GetCCListRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetCCTransactionList", new object[] {
                    GetCCListRequest}, callback, asyncState);
        }

        /// <remarks/>
        public GetCCListResponse EndGetCCTransactionList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetCCListResponse)(results[0]));
        }

        /// <remarks/>
        public void GetCCTransactionListAsync(GetCCListRequest GetCCListRequest)
        {
            this.GetCCTransactionListAsync(GetCCListRequest, null);
        }

        /// <remarks/>
        public void GetCCTransactionListAsync(GetCCListRequest GetCCListRequest, object userState)
        {
            if ((this.GetCCTransactionListOperationCompleted == null))
            {
                this.GetCCTransactionListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCCTransactionListOperationCompleted);
            }
            this.InvokeAsync("GetCCTransactionList", new object[] {
                    GetCCListRequest}, this.GetCCTransactionListOperationCompleted, userState);
        }

        private void OnGetCCTransactionListOperationCompleted(object arg)
        {
            if ((this.GetCCTransactionListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCCTransactionListCompleted(this, new GetCCTransactionListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vcs.co.za/wscs/svc_virtualrecur.asmx/GetCCTransactionDetail", RequestNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", ResponseNamespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetCCDetailResponse GetCCTransactionDetail(GetCCDetailRequest GetCCDetailRequest)
        {
            object[] results = this.Invoke("GetCCTransactionDetail", new object[] {
                    GetCCDetailRequest});
            return ((GetCCDetailResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetCCTransactionDetail(GetCCDetailRequest GetCCDetailRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetCCTransactionDetail", new object[] {
                    GetCCDetailRequest}, callback, asyncState);
        }

        /// <remarks/>
        public GetCCDetailResponse EndGetCCTransactionDetail(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetCCDetailResponse)(results[0]));
        }

        /// <remarks/>
        public void GetCCTransactionDetailAsync(GetCCDetailRequest GetCCDetailRequest)
        {
            this.GetCCTransactionDetailAsync(GetCCDetailRequest, null);
        }

        /// <remarks/>
        public void GetCCTransactionDetailAsync(GetCCDetailRequest GetCCDetailRequest, object userState)
        {
            if ((this.GetCCTransactionDetailOperationCompleted == null))
            {
                this.GetCCTransactionDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCCTransactionDetailOperationCompleted);
            }
            this.InvokeAsync("GetCCTransactionDetail", new object[] {
                    GetCCDetailRequest}, this.GetCCTransactionDetailOperationCompleted, userState);
        }

        private void OnGetCCTransactionDetailOperationCompleted(object arg)
        {
            if ((this.GetCCTransactionDetailCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCCTransactionDetailCompleted(this, new GetCCTransactionDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class AddCCRequest
    {

        private string userNameField;

        private string passwordField;

        private string userIDField;

        private string referenceNumberField;

        private string cardNumberField;

        private string cardExpiryYYField;

        private string cardExpiryMMField;

        private decimal amountField;

        private string cVCField;

        private string cardHolderNameField;

        private string cardHolderEmailField;

        private string descrOfGoodsField;

        private string startDateField;

        private string endDateField;

        private string occurCountField;

        private string frequencyField;

        private string merchantVar1Field;

        private string merchantVar2Field;

        private string merchantVar3Field;

        private string merchantVar4Field;

        private string merchantVar5Field;

        private string merchantVar6Field;

        private string merchantVar7Field;

        private string merchantVar8Field;

        private string merchantVar9Field;

        private string merchantVar10Field;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string ReferenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }

        /// <remarks/>
        public string CardNumber
        {
            get
            {
                return this.cardNumberField;
            }
            set
            {
                this.cardNumberField = value;
            }
        }

        /// <remarks/>
        public string CardExpiryYY
        {
            get
            {
                return this.cardExpiryYYField;
            }
            set
            {
                this.cardExpiryYYField = value;
            }
        }

        /// <remarks/>
        public string CardExpiryMM
        {
            get
            {
                return this.cardExpiryMMField;
            }
            set
            {
                this.cardExpiryMMField = value;
            }
        }

        /// <remarks/>
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        public string CVC
        {
            get
            {
                return this.cVCField;
            }
            set
            {
                this.cVCField = value;
            }
        }

        /// <remarks/>
        public string CardHolderName
        {
            get
            {
                return this.cardHolderNameField;
            }
            set
            {
                this.cardHolderNameField = value;
            }
        }

        /// <remarks/>
        public string CardHolderEmail
        {
            get
            {
                return this.cardHolderEmailField;
            }
            set
            {
                this.cardHolderEmailField = value;
            }
        }

        /// <remarks/>
        public string DescrOfGoods
        {
            get
            {
                return this.descrOfGoodsField;
            }
            set
            {
                this.descrOfGoodsField = value;
            }
        }

        /// <remarks/>
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        public string OccurCount
        {
            get
            {
                return this.occurCountField;
            }
            set
            {
                this.occurCountField = value;
            }
        }

        /// <remarks/>
        public string Frequency
        {
            get
            {
                return this.frequencyField;
            }
            set
            {
                this.frequencyField = value;
            }
        }

        /// <remarks/>
        public string MerchantVar1
        {
            get
            {
                return this.merchantVar1Field;
            }
            set
            {
                this.merchantVar1Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar2
        {
            get
            {
                return this.merchantVar2Field;
            }
            set
            {
                this.merchantVar2Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar3
        {
            get
            {
                return this.merchantVar3Field;
            }
            set
            {
                this.merchantVar3Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar4
        {
            get
            {
                return this.merchantVar4Field;
            }
            set
            {
                this.merchantVar4Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar5
        {
            get
            {
                return this.merchantVar5Field;
            }
            set
            {
                this.merchantVar5Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar6
        {
            get
            {
                return this.merchantVar6Field;
            }
            set
            {
                this.merchantVar6Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar7
        {
            get
            {
                return this.merchantVar7Field;
            }
            set
            {
                this.merchantVar7Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar8
        {
            get
            {
                return this.merchantVar8Field;
            }
            set
            {
                this.merchantVar8Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar9
        {
            get
            {
                return this.merchantVar9Field;
            }
            set
            {
                this.merchantVar9Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar10
        {
            get
            {
                return this.merchantVar10Field;
            }
            set
            {
                this.merchantVar10Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class GetCCDetailResponse
    {

        private string userNameField;

        private string passwordField;

        private string userIDField;

        private string referenceNumberField;

        private string cardNumberField;

        private decimal amountField;

        private string cardHolderNameField;

        private string cardHolderEmailField;

        private string descrOfGoodsField;

        private string startDateField;

        private string endDateField;

        private string occurCountField;

        private string frequencyField;

        private string suspendedField;

        private string suspendedDateField;

        private string deletedField;

        private string merchantVar1Field;

        private string merchantVar2Field;

        private string merchantVar3Field;

        private string merchantVar4Field;

        private string merchantVar5Field;

        private string merchantVar6Field;

        private string merchantVar7Field;

        private string merchantVar8Field;

        private string merchantVar9Field;

        private string merchantVar10Field;

        private string resultCodeField;

        private string resultMessageField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string ReferenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }

        /// <remarks/>
        public string CardNumber
        {
            get
            {
                return this.cardNumberField;
            }
            set
            {
                this.cardNumberField = value;
            }
        }

        /// <remarks/>
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        public string CardHolderName
        {
            get
            {
                return this.cardHolderNameField;
            }
            set
            {
                this.cardHolderNameField = value;
            }
        }

        /// <remarks/>
        public string CardHolderEmail
        {
            get
            {
                return this.cardHolderEmailField;
            }
            set
            {
                this.cardHolderEmailField = value;
            }
        }

        /// <remarks/>
        public string DescrOfGoods
        {
            get
            {
                return this.descrOfGoodsField;
            }
            set
            {
                this.descrOfGoodsField = value;
            }
        }

        /// <remarks/>
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        public string OccurCount
        {
            get
            {
                return this.occurCountField;
            }
            set
            {
                this.occurCountField = value;
            }
        }

        /// <remarks/>
        public string Frequency
        {
            get
            {
                return this.frequencyField;
            }
            set
            {
                this.frequencyField = value;
            }
        }

        /// <remarks/>
        public string Suspended
        {
            get
            {
                return this.suspendedField;
            }
            set
            {
                this.suspendedField = value;
            }
        }

        /// <remarks/>
        public string SuspendedDate
        {
            get
            {
                return this.suspendedDateField;
            }
            set
            {
                this.suspendedDateField = value;
            }
        }

        /// <remarks/>
        public string Deleted
        {
            get
            {
                return this.deletedField;
            }
            set
            {
                this.deletedField = value;
            }
        }

        /// <remarks/>
        public string MerchantVar1
        {
            get
            {
                return this.merchantVar1Field;
            }
            set
            {
                this.merchantVar1Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar2
        {
            get
            {
                return this.merchantVar2Field;
            }
            set
            {
                this.merchantVar2Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar3
        {
            get
            {
                return this.merchantVar3Field;
            }
            set
            {
                this.merchantVar3Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar4
        {
            get
            {
                return this.merchantVar4Field;
            }
            set
            {
                this.merchantVar4Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar5
        {
            get
            {
                return this.merchantVar5Field;
            }
            set
            {
                this.merchantVar5Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar6
        {
            get
            {
                return this.merchantVar6Field;
            }
            set
            {
                this.merchantVar6Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar7
        {
            get
            {
                return this.merchantVar7Field;
            }
            set
            {
                this.merchantVar7Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar8
        {
            get
            {
                return this.merchantVar8Field;
            }
            set
            {
                this.merchantVar8Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar9
        {
            get
            {
                return this.merchantVar9Field;
            }
            set
            {
                this.merchantVar9Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar10
        {
            get
            {
                return this.merchantVar10Field;
            }
            set
            {
                this.merchantVar10Field = value;
            }
        }

        /// <remarks/>
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class GetCCDetailRequest
    {

        private string userNameField;

        private string passwordField;

        private string userIDField;

        private string referenceNumberField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string ReferenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class GetCCListResponse
    {

        private System.Data.DataTable dataField;

        private string resultCodeField;

        private string resultMessageField;

        /// <remarks/>
        public System.Data.DataTable Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class GetCCListRequest
    {

        private string userNameField;

        private string passwordField;

        private string userIDField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class DeleteCCResponse
    {

        private string resultCodeField;

        private string resultMessageField;

        /// <remarks/>
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class DeleteCCRequest
    {

        private string userNameField;

        private string passwordField;

        private string userIDField;

        private string referenceNumberField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string ReferenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class ActivateCCResponse
    {

        private string resultCodeField;

        private string resultMessageField;

        /// <remarks/>
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class ActivateCCRequest
    {

        private string userNameField;

        private string passwordField;

        private string userIDField;

        private string referenceNumberField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string ReferenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class SuspendCCResponse
    {

        private string resultCodeField;

        private string resultMessageField;

        /// <remarks/>
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class SuspendCCRequest
    {

        private string userNameField;

        private string passwordField;

        private string userIDField;

        private string referenceNumberField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string ReferenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class UnSuspendCCResponse
    {

        private string resultCodeField;

        private string resultMessageField;

        /// <remarks/>
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class UnSuspendCCRequest
    {

        private string userNameField;

        private string passwordField;

        private string userIDField;

        private string referenceNumberField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string ReferenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class UpdateCCNumberResponse
    {

        private string resultCodeField;

        private string resultMessageField;

        /// <remarks/>
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class UpdateCCNumberRequest
    {

        private string userNameField;

        private string passwordField;

        private string userIDField;

        private string referenceNumberField;

        private string cardNumberField;

        private string cardExpiryYYField;

        private string cardExpiryMMField;

        private string cVCField;

        private string cardHolderNameField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string ReferenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }

        /// <remarks/>
        public string CardNumber
        {
            get
            {
                return this.cardNumberField;
            }
            set
            {
                this.cardNumberField = value;
            }
        }

        /// <remarks/>
        public string CardExpiryYY
        {
            get
            {
                return this.cardExpiryYYField;
            }
            set
            {
                this.cardExpiryYYField = value;
            }
        }

        /// <remarks/>
        public string CardExpiryMM
        {
            get
            {
                return this.cardExpiryMMField;
            }
            set
            {
                this.cardExpiryMMField = value;
            }
        }

        /// <remarks/>
        public string CVC
        {
            get
            {
                return this.cVCField;
            }
            set
            {
                this.cVCField = value;
            }
        }

        /// <remarks/>
        public string CardHolderName
        {
            get
            {
                return this.cardHolderNameField;
            }
            set
            {
                this.cardHolderNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class UpdateCCResponse
    {

        private string resultCodeField;

        private string resultMessageField;

        /// <remarks/>
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class UpdateCCRequest
    {

        private string userNameField;

        private string passwordField;

        private string userIDField;

        private string referenceNumberField;

        private decimal amountField;

        private string cardHolderNameField;

        private string cardHolderEmailField;

        private string descrOfGoodsField;

        private string startDateField;

        private string endDateField;

        private string occurCountField;

        private string frequencyField;

        private string merchantVar1Field;

        private string merchantVar2Field;

        private string merchantVar3Field;

        private string merchantVar4Field;

        private string merchantVar5Field;

        private string merchantVar6Field;

        private string merchantVar7Field;

        private string merchantVar8Field;

        private string merchantVar9Field;

        private string merchantVar10Field;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string ReferenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }

        /// <remarks/>
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        public string CardHolderName
        {
            get
            {
                return this.cardHolderNameField;
            }
            set
            {
                this.cardHolderNameField = value;
            }
        }

        /// <remarks/>
        public string CardHolderEmail
        {
            get
            {
                return this.cardHolderEmailField;
            }
            set
            {
                this.cardHolderEmailField = value;
            }
        }

        /// <remarks/>
        public string DescrOfGoods
        {
            get
            {
                return this.descrOfGoodsField;
            }
            set
            {
                this.descrOfGoodsField = value;
            }
        }

        /// <remarks/>
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        public string OccurCount
        {
            get
            {
                return this.occurCountField;
            }
            set
            {
                this.occurCountField = value;
            }
        }

        /// <remarks/>
        public string Frequency
        {
            get
            {
                return this.frequencyField;
            }
            set
            {
                this.frequencyField = value;
            }
        }

        /// <remarks/>
        public string MerchantVar1
        {
            get
            {
                return this.merchantVar1Field;
            }
            set
            {
                this.merchantVar1Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar2
        {
            get
            {
                return this.merchantVar2Field;
            }
            set
            {
                this.merchantVar2Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar3
        {
            get
            {
                return this.merchantVar3Field;
            }
            set
            {
                this.merchantVar3Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar4
        {
            get
            {
                return this.merchantVar4Field;
            }
            set
            {
                this.merchantVar4Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar5
        {
            get
            {
                return this.merchantVar5Field;
            }
            set
            {
                this.merchantVar5Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar6
        {
            get
            {
                return this.merchantVar6Field;
            }
            set
            {
                this.merchantVar6Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar7
        {
            get
            {
                return this.merchantVar7Field;
            }
            set
            {
                this.merchantVar7Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar8
        {
            get
            {
                return this.merchantVar8Field;
            }
            set
            {
                this.merchantVar8Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar9
        {
            get
            {
                return this.merchantVar9Field;
            }
            set
            {
                this.merchantVar9Field = value;
            }
        }

        /// <remarks/>
        public string MerchantVar10
        {
            get
            {
                return this.merchantVar10Field;
            }
            set
            {
                this.merchantVar10Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.vcs.co.za/wscs/svc_virtualrecur.asmx")]
    public partial class AddCCResponse
    {

        private string resultCodeField;

        private string resultMessageField;

        /// <remarks/>
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void AddCCTransactionCompletedEventHandler(object sender, AddCCTransactionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCCTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal AddCCTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public AddCCResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((AddCCResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void UpdateCCTransactionCompletedEventHandler(object sender, UpdateCCTransactionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCCTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UpdateCCTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public UpdateCCResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((UpdateCCResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void UpdateCCNumberCompletedEventHandler(object sender, UpdateCCNumberCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCCNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UpdateCCNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public UpdateCCNumberResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((UpdateCCNumberResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void UnSuspendCCTransactionCompletedEventHandler(object sender, UnSuspendCCTransactionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnSuspendCCTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UnSuspendCCTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public UnSuspendCCResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((UnSuspendCCResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void SuspendCCTransactionCompletedEventHandler(object sender, SuspendCCTransactionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuspendCCTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SuspendCCTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SuspendCCResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SuspendCCResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void ActivateCCTransactionCompletedEventHandler(object sender, ActivateCCTransactionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivateCCTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ActivateCCTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ActivateCCResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ActivateCCResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void DeleteCCTransactionCompletedEventHandler(object sender, DeleteCCTransactionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCCTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DeleteCCTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public DeleteCCResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DeleteCCResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void GetCCTransactionListCompletedEventHandler(object sender, GetCCTransactionListCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCCTransactionListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetCCTransactionListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public GetCCListResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((GetCCListResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void GetCCTransactionDetailCompletedEventHandler(object sender, GetCCTransactionDetailCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCCTransactionDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetCCTransactionDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public GetCCDetailResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((GetCCDetailResponse)(this.results[0]));
            }
        }
    }
}

    
